### ISSUE TITLE
How about different cv of herta

### ISSUE THREAD

**Issue by Prohect** [duiqt/herta_kuru#13]
Like put a checklist 2 switch cv between en,cn,jp , like that.
It will be really cool if u do LOL.

**Comment by Zhaokugua** [comment]
[herta_kuru_cn_voice.zip](https://github.com/duiqt/herta_kuru/files/11576804/herta_kuru_cn_voice.zip)
cn_voice unpacked from the game
if u need=w=

**Comment by fred913** [comment]
I solved it by my Pull Request #15 .
