### ISSUE TITLE
[Need Help] Korean support needed

### ISSUE THREAD

**Issue by fred913** [duiqt/herta_kuru#16]
As per the script.js file, we are eagerly anticipating the translation of the page and voice files for the mentioned languages.
If you have the audio files and are proficient in those languages, please feel free to edit script.js, upload the necessary assets, and create a PR. Thank you very much!

### Current Progress
- [X] Japanese
- [x] Korean

**Comment by vgwik** [comment]
## JS日本語バージョン
```
    const LANGUAGES = {
    "ja": {
        audioList: [
            new Audio("audio/ja/kuruto.mp3"),
            new Audio("audio/ja/kuru1.mp3"),
            new Audio("audio/ja/kuru2.mp3"),
        ],
        texts: {
            "page-title": "ヘルタクルへようこそ~",
            "doc-title": "クル クル~",
            "page-descriptions": "このサイトはヘルタのために作られた、 あの崩壊：スターレイルの <del>悩ましい</del> かわいい天才キャラー。",
            "counter-descriptions": "全世界のクル再生数",
            "counter-unit": "回",
            "counter-button": "クル クル~!",
            "credits-gif": "GIF作成者は",
            "footer-repository-text": "こちはこのページGitHubリポジトリ:",
            "footer-repository-text-2": "herta_kuru リポジトリ"
        }
    }
};
```

**Comment by fred913** [comment]
@vgwik 感谢，不过怎么下日语语音？崩星这目录好难翻

(thanks but how can I get the Japanese voice files from the weird structures of folders in HS)

**Comment by vgwik** [comment]
我都是用OBS内录的，而且，好像原网站就是英语界面加日语语音。
我不知道国际服的拿这个车票的网站在哪里，现在暂时弄不到日语车票。
I use OBS to record audios, and the website looks like use ENGLISH and JAPANESE VC.
idk where the HS website of ASIA Service is to get Japanese ticket. I can't get it right now.

**Comment by vgwik** [comment]
@fred913 如果你有做下一次提交的话，把日语选项里面的“こちはこのページGitHubリポジトリ:”
改成“こちらはこのページGitHubリポジトリ:”，我打错了，不过这个是小问题，所以暂时不改问题不大。

**Comment by fred913** [comment]
原作者没给我write access，待会如果做pr的话一定顺带带上

**Comment by PencilCore** [comment]
有会韩语的也可以帮忙，就差这一个了。
Only Korean left, need contributers.

**Comment by vgwik** [comment]
# Korean Ticket
![card_kr](https://github.com/duiqt/herta_kuru/assets/52212950/89a0e84f-4cf3-4729-8363-60f2b2e6bae7)

**Comment by PencilCore** [comment]
> # Korean Ticket
> ![card_kr](https://user-images.githubusercontent.com/52212950/241576289-89a0e84f-4cf3-4729-8363-60f2b2e6bae7.jpg)

😍

**Comment by vgwik** [comment]
韩语翻译：
提供者：[提灯书梦](https://space.bilibili.com/6318620)
```
const LANGUAGES = {
    "kr": {
        audioList: [
            new Audio("audio/kr/kuruto.mp3"),
            new Audio("audio/kr/kuru1.mp3"),
            new Audio("audio/kr/kuru2.mp3"),
        ], 헤르타
        texts: {
            "page-title": "헤르타빙글 환영합니다~",
            "doc-title": "빙글 빙글~",
            "page-descriptions": "이 웹사이트는 헤르타를 위해 만들어졌습니다, 붕괴: 스타레일 의 <del>귀찮은</del> 귀여운 천재 ",
            "counter-descriptions": "전 세계 빙글 조회수",
            "counter-unit": "번",
            "counter-button": "빙글 빙글~!",
            "credits-gif": "gif의 제작자입니다",
            "footer-repository-text": "여기 github 데이터베이스가 있습니다:",
            "footer-repository-text-2": "herta_kuru 데이터 베이스"
        }
    }

```

**Comment by duiqt** [comment]
Only the audio left then we're good to go.

**Comment by fred913** [comment]
Yes.

**Comment by vgwik** [comment]
# 翻译补充 | Translation addition
@fred913 补充了位于网页最底部的 **镜像站(Mirror site)** 翻译。
## 日语翻译 | Japanese
此翻译由 <img src="https://i1.hdslb.com/bfs/face/5772af8e0ad4067323e1f082f887a220b92dbf71.jpg" alt="二次元のリア充"
title="二次元のリア充" width="20px" height="20px" style="border-radius:50%;padding-top: 0px;">[二次元のリア充](https://space.bilibili.com/7885894) 提供 | Translation provider
```
"ja": {
    audioList: [
    ],
    texts: {
        "access-via-pages": "今アクセスしてるページはぎGitHubです。中国大陸まだは他の地域のユーサーはNetlifyのミラーに入るために、<a href='https://herta.ft2.ltd/'>ここにクリックして</a>ください。",
        "access-via-mirror": "おめでとうございます！今はもうミラーサイトを使っています、中国大陸まだは他の地域のアクセス速度が速くなります。サイトのソースを見たいなら、<a href='https://duiqt.github.io/herta_kuru/'>ここにクリックして</a>、GitHubページで見てください。"
    },
    cardImage: "img/card_ja.jpg"
}
```
## 韩语翻译 | Korean
此翻译由 <img src="https://i2.hdslb.com/bfs/face/d3f6572157f3c51497cff1d58dd925632477faf5.jpg" alt="提灯书梦"
title="提灯书梦" width="20px" height="20px" style="border-radius:50%;padding-top: 0px;">[提灯书梦](https://space.bilibili.com/6318620) 提供 | Translation provider
```
"kr": {
    audioList: [
    ],
    texts: {
        "access-via-pages": "당신은 GitHub를 통해 액세스하고 있습니다. 중국 또는 기타 지역 사용자의 경우 여기를 <a href='https://herta.ft2.ltd/'>클릭하여 Netlify의 미러 액세스하십시오</a>. ",
        "access-via-mirror": "축하합니다. 당신은 미러 웹 사이트를 통해 액세스하고 있습니다, 이렇게 하면 중국 및 일부 다른 지역에서의 액세스 속도가 빨라집니다. 여기를 <a href='https://duiqt.github.io/herta_kuru/'> 클릭하여 GitHub의 소스 페이지에 액세스하십시오</a>. "
    },
    cardImage: "img/card_kr.jpg"
}
```

**Comment by fred913** [comment]
Thanks!! You're awesome!

**Comment by fred913** [comment]
They'll be implemented today along with the credits page

**Comment by fred913** [comment]
好滴
老哥你会写前端不，html和css，我credits写不完了，能来帮下忙不？
看我的fork就行，好了交个pr，谢谢了

**Comment by vgwik** [comment]
头像拿B站的，不要直接复制链接粘贴，直接粘贴是压缩属性
以这个为例，下面这个是压缩过大小的头像
>//i1.hdslb.com/bfs/face/5772af8e0ad4067323e1f082f887a220b92dbf71.jpg@240w_240h_1c_1s_!web-avatar-space-header.webp

下面这个是在原来的基础上，去掉了@后面的那一串，得到的就是没有压缩的

>//i1.hdslb.com/bfs/face/5772af8e0ad4067323e1f082f887a220b92dbf71.jpg

**Comment by fred913** [comment]
你说的对，但是前端是80×80px的头像展示，理论上不需要那么大的图片尺寸

**Comment by fred913** [comment]
Korean support is on the same progress as English (text+ticket) now.
