### ISSUE TITLE
Delay in first time clicking the kuru button

### ISSUE THREAD

**Issue by LorenzoValentine** [duiqt/herta_kuru#31]
For some of my devices(Both Windows Desktop and Mac), every time I enter the website and click the 'Kuru' button for the first time, although Herta's animation runs smoothly, the first time Herta makes a sound may be delayed or even start playing from halfway.

**Comment by Zhaokugua** [comment]
> For some of my devices(Both Windows Desktop and Mac), every time I enter the website and click the 'Kuru' button for the first time, although Herta's animation runs smoothly, the first time Herta makes a sound may be delayed or even start playing from halfway.

或许是因为连接到github pages的网络太慢导致第一声语音没加载出来？

**Comment by fred913** [comment]
@Zhaokugua Yes, exactly. Now I'm working on caching, building a mirror inside China.

**Comment by LorenzoValentine** [comment]
但是我不在中国大陆 在澳洲 一般来讲不会有这样的问题
> > For some of my devices(Both Windows Desktop and Mac), every time I enter the website and click the 'Kuru' button for the first time, although Herta's animation runs smoothly, the first time Herta makes a sound may be delayed or even start playing from halfway.
> 
> 
> 
> 或许是因为连接到github pages的网络太慢导致第一声语音没加载出来？

**Comment by george-chou** [comment]
Here is a solution I have, please refer to the following video: https://www.bilibili.com/video/BV1FW4y1Q7Dj. If you are willing to add me as a contributor to your project, I am happy to contribute this technology to your repository.

**Comment by george-chou** [comment]
fixed by #77
