### ISSUE TITLE
jumping 'github.io' to 'herta.ft2.ltd' may impact others' debugging

### ISSUE THREAD

**Issue by monetjoe** [duiqt/herta_kuru#70]
Thanks for your reminding @vgwik 
Here shows your video for reproducing the problem:

https://github.com/duiqt/herta_kuru/assets/20459298/b561b15a-326b-4540-8c8d-3ff28553acf6

**Comment by george-chou** [comment]
![Snipaste_2023-06-14_22-41-45](https://github.com/duiqt/herta_kuru/assets/20459298/53b8c0ad-581d-4360-9d03-7824aa65b648)

I shall change this jumping into the one only for 'https://duiqt.github.io/herta_kuru'
