### ISSUE TITLE
No "Kuru kuru~!" buttom?

### ISSUE THREAD

**Issue by jhone22323232354** [duiqt/herta_kuru#86]
I build this website in my raspberrypi,i use nginx,and the system is rockylinux.But in my website,i can't find the "Kuru kuru~!" buttom.
![QQ截图20230704021301](https://github.com/duiqt/herta_kuru/assets/44319036/df9977dc-cf47-40bb-b825-4604b9beb904)

**Comment by george-chou** [comment]
#84 has fixed this problem, please use the latest version of main branch
