### ISSUE TITLE
UI of settings window can be improved

### ISSUE THREAD

**Issue by idevkshitij** [duiqt/herta_kuru#87]
Hey! In the settings pop up window the Title and Drop-Down text looks a bit cluttered with the close spacing.
I suggest to add a Delimiter for the same like " : " or " - " or any of your suggestions.
I would be happy to contribute the changes if you can assign it to me.

![image](https://github.com/duiqt/herta_kuru/assets/74612148/54ca775c-1579-4c16-b98c-fbc4d8449496)

**Comment by fred913** [comment]
It should be solved in #88.

**Comment by idevkshitij** [comment]
Oh I didn't see the opened issue earlier. Thus, raised one.

**Comment by fred913** [comment]
Not your fault haha
I meant that I solved the issue according to your instructions.

**Comment by fred913** [comment]
I'm going to close this if the problem is solved. If it's then not working as planned, reopening is also welcomed.
